### ISSUE TITLE
The website SSL certificate has expired

### ISSUE THREAD

**Issue by PossiblyMax** [solomon-gumball/timeline-css#1]
Hiya - big fan of the app, has really helped me with some animations.

Just wanted to give you a heads up in case you weren't aware, the SSL cert on the hosted site has expired and is coming up with an error.

Cheers!

**Comment by solomon-gumball** [comment]
Hey thanks for the heads up I'll address that today 👍  Glad you've enjoyed using it!

**Comment by solomon-gumball** [comment]
Finally got to it thanks for waiting!  https://www.timelinecss.io
